name: Just Push Play
favicon: null
layout_spectrum: 0.0701436570379883
typography_spectrum: 0.5065238303504884
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ADD7F6'
    - '#87BFFF'
    - '#3F8EFC'
    - '#2667FF'
    - '#3B28CC'
  brandStrength: 0.49380806856788695
  lightness: 0.4422677068505436
  saturation: 0.09703223058022559
  rhythmicContrast: 0.5841181583236903
purpose: []
